# Use Node.js for building, then serve with Nginx
FROM node:16-alpine AS frontend

# Accept the IP as build argument
ARG PUBLIC_IP
# Set as environment variable
ENV REACT_APP_API_URL=http://${PUBLIC_IP}:3001

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./

# clear cache and Install dependencies
RUN npm cache clean --force
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Build the frontend
RUN npm run build

# Serve with Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend /app/build /usr/share/nginx/html
EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]
