# Stage 1: Build React App
FROM node:16-alpine AS frontend

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Inject the build argument
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build


# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend /app/build /usr/share/nginx/html


EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]
