version: '3.8'

services:
  backend:
    working_dir: /app
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}  # ✅ Pass build arg
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - backend
    env_file:
      - ./.env
