version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-deploy:
    executor: docker-executor
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - setup_remote_docker

      # Login to Docker Hub
      - run:
          name: Docker login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      # Detect changes and build/push only changed tier
      - run:
          name: Build & Push Only Changed Tier
          command: |
            git fetch origin main
            CHANGED=$(git diff --name-only origin/main...HEAD)

            FRONTEND_CHANGED=false
            BACKEND_CHANGED=false

            echo "$CHANGED" | grep -q '^frontend/' && FRONTEND_CHANGED=true
            echo "$CHANGED" | grep -q '^backend/' && BACKEND_CHANGED=true

            if $FRONTEND_CHANGED; then
              echo "Frontend changed"
              docker build -t kuzan0069/dream-vacation-frontend ./frontend
              docker push kuzan0069/dream-vacation-frontend
            fi

            if $BACKEND_CHANGED; then
              echo "Backend changed"
              docker build -t kuzan0069/dream-vacation-backend ./backend
              docker push kuzan0069/dream-vacation-backend
            fi

            echo "$FRONTEND_CHANGED" > frontend_changed.flag
            echo "$BACKEND_CHANGED" > backend_changed.flag

      # Persist change flags
      - persist_to_workspace:
          root: .
          paths:
            - frontend_changed.flag
            - backend_changed.flag

  deploy-to-ec2:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "SHA256:Z4A+Ef7DJZ3N5AtxlC9ISZK/wS6owpq10wDCPtxhTyw"

      - run:
          name: Deploy Only Changed Tier to EC2
          command: |
            FRONTEND=$(cat frontend_changed.flag)
            BACKEND=$(cat backend_changed.flag)

            if [ "$FRONTEND" = "true" ]; then
              ssh -o StrictHostKeyChecking=no ec2-user@13.53.38.76 "
                docker pull kuzan0069/dream-vacation-frontend &&
                docker rm -f dream-vacation-frontend || true &&
                docker run -d -p 80:80 --name dream-vacation-frontend kuzan0069/dream-vacation-frontend
              "
            fi

            if [ "$BACKEND" = "true" ]; then
              ssh -o StrictHostKeyChecking=no ec2-user@13.53.38.76 "
                docker pull kuzan0069/dream-vacation-backend &&
                docker rm -f dream-vacation-backend || true &&
                docker run -d -p 3001:3001 --name dream-vacation-backend kuzan0069/dream-vacation-backend
              "
            fi

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
      - deploy-to-ec2:
          requires:
            - build-and-deploy
