version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker

      # Login to Docker Hub
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      # Build Frontend (if frontend/ changed)
      - run:
          name: Build Frontend with Dynamic IP
          command: |
            if git diff --name-only HEAD~1 | grep -q "^frontend/"; then
              CURRENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "fallback.ip.here")
              docker build \
                --build-arg PUBLIC_IP=$CURRENT_IP \
                -t $DOCKERHUB_USER/dream-vacation-frontend:latest \
                ./frontend
              docker push $DOCKERHUB_USER/dream-vacation-frontend:latest
              echo "Frontend image updated"
            else
              echo "No frontend changes - skipping build"
            fi

      # Build Backend (if backend/ changed)
      - run:
          name: Build Backend
          command: |
            if git diff --name-only HEAD~1 | grep -q "^backend/"; then
              docker build -t $DOCKERHUB_USER/dream-vacation-backend:latest ./backend
              docker push $DOCKERHUB_USER/dream-vacation-backend:latest
              echo "Backend image updated"
            else
              echo "No backend changes - skipping build"
            fi

workflows:
  build-only:
    jobs:
      - build-and-push